/**
 * My Doctor API
 * My Doctor API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateAppointmentOrderDto { 
    /**
     * Start Time
     */
    startTime: Date;
    /**
     * End Time
     */
    endTime: Date;
    /**
     * Doctor Id
     */
    doctorUserId: number;
    /**
     * Patient/User ID
     */
    patientUserId: number;
    /**
     * Consultation ID
     */
    consultationId: number;
}

