/**
 * My Doctor API
 * My Doctor API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DoctorProfileDto { 
    /**
     * The user ID who owns the doctor profile
     */
    userId: number;
    /**
     * Doctor profile ID (different than user ID
     */
    id: number;
    /**
     * Medical Council ID
     */
    medicalCouncilId: number;
    /**
     * Medical Registration ID
     */
    medicalRegistrationNumber: string;
    /**
     * Organization ID
     */
    organizationId: number;
    /**
     * Branch ID
     */
    imaBranchId: number;
    /**
     * Type of User ID (Aadhar, PAN etc.)
     */
    userIdTypeId: number;
    /**
     * User ID Number (Aadhar, PAN etc.)
     */
    userIdNumber: string;
    /**
     * Description
     */
    description: string;
    /**
     * Keywords (Comma separated)
     */
    keywords: string;
}

