/**
 * My Doctor API
 * My Doctor API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InlineResponse200 { 
    status?: string;
    info?: { [key: string]: { [key: string]: string; }; } | null;
    error?: { [key: string]: { [key: string]: string; }; } | null;
    details?: { [key: string]: { [key: string]: string; }; };
}

