/**
 * My Doctor API
 * My Doctor API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PatientProfileDto { 
    /**
     * Type of User ID (Aadhar, PAN etc.)
     */
    userIdTypeId?: number;
    /**
     * User ID Number (Aadhar, PAN etc.)
     */
    userIdNumber?: string;
    /**
     * Height
     */
    height?: string;
    /**
     * Weight
     */
    weight?: string;
    /**
     * Clinical Notes
     */
    clinicalNotes?: string;
}

