/**
 * My Doctor API
 * My Doctor API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PatientFilterDto { 
    /**
     * Doctor ID for which we need patient list
     */
    doctorUserId?: number;
    /**
     * Page number/offer
     */
    limit?: number;
    /**
     * Page number/offer
     */
    page?: number;
}

