/**
 * My Doctor API
 * My Doctor API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SignUpDto { 
    /**
     * User Name
     */
    username: string;
    /**
     * User Password
     */
    password: string;
    /**
     * Role of user
     */
    role: string;
    /**
     * Email
     */
    email?: string;
    /**
     * Full Name
     */
    fullname: string;
    /**
     * Referral Code. If it is valid it will be linked with account.
     */
    signupReferralCode?: string;
}

