/**
 * My Doctor API
 * My Doctor API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SiteStats { 
    /**
     * Number of doctors
     */
    doctors: number;
    /**
     * Number of users
     */
    users: number;
    /**
     * Number of providers
     */
    providers: number;
    /**
     * Number of completed (COMPLETED) appointments
     */
    completedAppointments: number;
    /**
     * Number of user cancelled (USER_CANCELLED) appointments
     */
    userCancelledAppointments: number;
    /**
     * Number of doctor cancelled (DOCTOR_CANCELLED) appointments
     */
    doctorCancelledAppointments: number;
    /**
     * Number of pending (ORDER_CREATED) appointments
     */
    orderCreatedAppointments: number;
    /**
     * Number of user paid (PAYMENT_RECEIVED) appointments
     */
    paymentReceivedAppointments: number;
}

