/**
 * My Doctor API
 * My Doctor API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UIDropDownTypes { 
    /**
     * Medical Councils
     */
    medicalCouncils: Array<string>;
    /**
     * IMA Branches
     */
    imaBranches: Array<string>;
    /**
     * Consultation Types
     */
    consultationTypes: Array<string>;
    /**
     * Organizations
     */
    organizations: Array<string>;
    /**
     * Qualifications
     */
    qualifications: Array<string>;
    /**
     * Specialities
     */
    specialities: Array<string>;
    /**
     * User ID Types
     */
    userIdTypes: Array<string>;
    /**
     * Genders
     */
    genders: Array<string>;
}

