/**
 * My Doctor API
 * My Doctor API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UpdateConsultationItem } from './updateConsultationItem';


export interface UpdateConsultationTypeDto { 
    /**
     * List of consultations IDs and start/end times
     */
    entries: Array<UpdateConsultationItem>;
}

