/**
 * My Doctor API
 * My Doctor API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateConsultationItem { 
    /**
     * Option Id
     */
    id: number;
    /**
     * Description
     */
    description: string;
    /**
     * Record ID to be updated
     */
    recordId?: number;
    /**
     * Start Time
     */
    startTime: Date;
    /**
     * End Time
     */
    endTime: Date;
    /**
     * Consultation Fees
     */
    fees: number;
}

