/**
 * My Doctor API
 * My Doctor API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserProfileDto { 
    /**
     * Full Name
     */
    fullname: string;
    /**
     * Gender ID
     */
    gender: number;
    /**
     * Street Address
     */
    streetAddress: string;
    /**
     * City
     */
    city: string;
    /**
     * Postal Code
     */
    postalCode: string;
    /**
     * State
     */
    state: string;
    /**
     * Country
     */
    country: string;
    /**
     * Latitude
     */
    lat: string;
    /**
     * Longitude
     */
    lon: string;
}

