export * from './account.service';
import { AccountService } from './account.service';
export * from './admin.service';
import { AdminService } from './admin.service';
export * from './appointment.service';
import { AppointmentService } from './appointment.service';
export * from './common.service';
import { CommonService } from './common.service';
export * from './default.service';
import { DefaultService } from './default.service';
export * from './doctorProfile.service';
import { DoctorProfileService } from './doctorProfile.service';
export * from './notification.service';
import { NotificationService } from './notification.service';
export * from './patientProfile.service';
import { PatientProfileService } from './patientProfile.service';
export * from './referrals.service';
import { ReferralsService } from './referrals.service';
export * from './tasks.service';
import { TasksService } from './tasks.service';
export * from './userProfile.service';
import { UserProfileService } from './userProfile.service';
export const APIS = [AccountService, AdminService, AppointmentService, CommonService, DefaultService, DoctorProfileService, NotificationService, PatientProfileService, ReferralsService, TasksService, UserProfileService];
